### ISSUE TITLE
Website UI out of order in mobile

### ISSUE THREAD

**Issue by angelofallars** [xyrelljoi/xyrelljoi.github.io#1]
Specifically on iPhone 7, iOS 14.6
![image](https://user-images.githubusercontent.com/39676098/128628030-c053fa74-5eb4-44ae-a723-4c7760709b11.png)

**Comment by xyrelljoi** [comment]
thanks! I still don't know how to arrange that by a mobile screen but I'll try to learn and fix it immediately.😅

**Comment by angelofallars** [comment]
You're welcome! If you need help with web development, you can join Bryl's Server in Discord. It's an active Filipino programming community full of web developers. You can ask them anything you need! [Join here](https://discord.gg/8255Jrnp)

**Comment by ayushmansxn01** [comment]
I have made your website Responsive !!!
Do check it out.😀

**Comment by xyrelljoi** [comment]
hey! @ayushmansxn01 thanks for helping♥️

**Comment by xyrelljoi** [comment]
@angelofallars thanks! i just recently joined your server, it's awesome. I hope I can learn more with the community♥️

**Comment by angelofallars** [comment]
Thanks @ayushmansxn01 again for helping me with my own repo and also helping in this! Once the pull requests have been merged and the mobile UI is finally fixed, I'll close this issue 👍
